name: Test dotnet APIs

on:
  workflow_call:
    inputs:
      path_to_project:
        required: true
        type: string

jobs:
  test_apis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path_to_project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build APIs
        run: dotnet build --no-restore Backend.sln
      - name: Test APIs
        run: dotnet test --no-restore --verbosity normal
