name: Test dotnet APIs

on:
  workflow_call:
    inputs:
      path_to_project:
        required: true
        type: string

jobs:
  test_apis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path_to_project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Init user secrets
        run: dotnet user-secrets -p FileStorageService init
      - name: Add Google Cloud Bucket name
        shell: bash
        env:
          GOOGLE_CLOUD_BUCKET_NAME: ${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}
        run: dotnet user-secrets -p FileStorageService set "GoogleCloud:BucketName" "$GOOGLE_CLOUD_BUCKET_NAME"
      - name: Add Google Cloud secrets
        shell: bash
        env:
          GOOGLE_CLOUD_SECRET: ${{ secrets.GOOGLE_CLOUD_SECRET }}
        run: dotnet user-secrets -p FileStorageService set "GoogleCloud:Secret" "$GOOGLE_CLOUD_SECRET"
      - name: Build APIs
        env:
          "GoogleCloud:BucketName": ${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}
          "GoogleCloud:Secret": ${{ secrets.GOOGLE_CLOUD_SECRET }}
        run: dotnet build --no-restore Backend.sln
      - name: Test APIs
        env:
          "GoogleCloud:BucketName": ${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}
          "GoogleCloud:Secret": ${{ secrets.GOOGLE_CLOUD_SECRET }}
        run: dotnet test --no-restore --no-build --verbosity normal
