name: Build and deploy backed API

on:
  workflow_call:
    inputs:
      path_to_project:
        default: apis/
        type: string
      project_name:
        required: true
        type: string
      dev_deploy:
        required: false
        type: boolean
        default: false
      google_cloud_bucket_name:
        type: string
        description: Name of a Google Cloud bucket name. It is needed for file storage.
        required: true
      google_cloud_secret_type:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_project_id:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_private_key_id:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_private_key:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_client_email:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_client_id:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_auth_uri:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_token_uri:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_auth_provider_x509_cert_url:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
      google_cloud_secret_client_x509_cert_url:
        type: string
        description: Google Cloud secret needed for file storage.
        required: true
    secrets:
      azure_app_service_publish_profile:
        required: true

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{inputs.path_to_project}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Secrets set up
        uses: ./.github/actions/set_up_apis_secrets
        with:
          google_cloud_bucket_name: ${{ google_cloud_bucket_name }}
          google_cloud_secret_type: ${{ google_cloud_secret_type }}
          google_cloud_secret_project_id: ${{ google_cloud_secret_project_id }}
          google_cloud_secret_private_key_id: ${{ google_cloud_secret_private_key_id }}
          google_cloud_secret_private_key: ${{ google_cloud_secret_private_key }}
          google_cloud_secret_client_email: ${{ google_cloud_secret_client_email }}
          google_cloud_secret_client_id: ${{ google_cloud_secret_client_id }}
          google_cloud_secret_auth_uri: ${{ google_cloud_secret_auth_uri }}
          google_cloud_secret_token_uri: ${{ google_cloud_secret_token_uri }}
          google_cloud_secret_auth_provider_x509_cert_url: ${{ google_cloud_secret_auth_provider_x509_cert_url }}
          google_cloud_secret_client_x509_cert_url: ${{ google_cloud_secret_client_x509_cert_url }}
      - name: Build with dotnet
        run: dotnet build --configuration Release ${{inputs.project_name}}
      - name: dotnet publish
        run: dotnet publish ${{inputs.project_name}} -c Release -o ${{env.DOTNET_ROOT}}/${{inputs.project_name}}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.project_name}}
          path: ${{env.DOTNET_ROOT}}/${{inputs.project_name}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      APP_NAME: 'petshare-${{inputs.project_name}}'

    steps:
      - name: Set dev app name
        if: ${{inputs.dev_deploy}}
        run: |
          chcp 65001 #set code page to utf-8
          echo ("APP_NAME=" + $env:APP_NAME + "-dev") >> $env:GITHUB_ENV

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{inputs.project_name}}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.APP_NAME}}
          slot-name: 'Production'
          publish-profile: ${{secrets.azure_app_service_publish_profile}}
          package: .
          images: ""
