name: Build and deploy backed API

on:
  workflow_call:
    inputs:
      path_to_project:
        default: apis/
        type: string
      project_name:
        required: true
        type: string
      dev_deploy:
        required: false
        type: boolean
        default: false
    secrets:
      azure_app_service_publish_profile:
        required: true
      google_bucket_name:
        required: true
      google_secret:
        required: true

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{inputs.path_to_project}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Init user secrets
        shell: bash
        run: dotnet user-secrets -p FileStorageService init
      - name: Add Google Cloud Bucket name
        shell: bash
        run: dotnet user-secrets -p FileStorageService set "GoogleCloud:BucketName" "${{ secrets.google_bucket_name }}"
      - name: Add Google Cloud secrets
        shell: bash
        run: dotnet user-secrets -p FileStorageService set "GoogleCloud:Secret" "${{ secrets.google_secret }}"
      - name: Build with dotnet
        run: dotnet build --configuration Release ${{inputs.project_name}}
      - name: dotnet publish
        run: dotnet publish ${{inputs.project_name}} -c Release -o ${{env.DOTNET_ROOT}}/${{inputs.project_name}}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.project_name}}
          path: ${{env.DOTNET_ROOT}}/${{inputs.project_name}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      APP_NAME: 'petshare-${{inputs.project_name}}'

    steps:
      - name: Set dev app name
        if: ${{inputs.dev_deploy}}
        run: |
          chcp 65001 #set code page to utf-8
          echo ("APP_NAME=" + $env:APP_NAME + "-dev") >> $env:GITHUB_ENV

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{inputs.project_name}}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.APP_NAME}}
          slot-name: 'Production'
          publish-profile: ${{secrets.azure_app_service_publish_profile}}
          package: .
          images: ""
