name: Dev merge workflows

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths:
      - "apis/**"
      - "!apis/API_tests/**"

jobs:
  deploy_shelter_api:
    uses: ./.github/workflows/deploy_API.yml
    with:
      project_name: ShelterAPI
      dev_deploy: true
    secrets:
      azure_app_service_publish_profile: ${{ secrets.PUBLISH_PROFILE_SHELTER_API_DEV }}
      google_bucket_name: ${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}
      google_secret: ${{ secrets.GOOGLE_CLOUD_SECRET }}
  
  deploy_announcements_api:
    uses: ./.github/workflows/deploy_API.yml
    with:
      project_name: AnnouncementsAPI
      dev_deploy: true
    secrets:
      azure_app_service_publish_profile: ${{ secrets.PUBLISH_PROFILE_ANNOUNCEMENT_API_DEV }}
      google_bucket_name: ${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}
      google_secret: ${{ secrets.GOOGLE_CLOUD_SECRET }}
  
  deploy_adopter_api:
    uses: ./.github/workflows/deploy_API.yml
    with:
      project_name: AdopterAPI
      dev_deploy: true
    secrets:
      azure_app_service_publish_profile: ${{ secrets.PUBLISH_PROFILE_ADOPTER_API_DEV }}
      google_bucket_name: ${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}
      google_secret: ${{ secrets.GOOGLE_CLOUD_SECRET }}
