name: Dev merge workflows

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths:
      - "apis/**"
      - "!apis/API_tests/**"

jobs:
  deploy_shelter_api:
    uses: ./.github/workflows/deploy_shelter.yml
    with:
      project_name: ShelterAPI
      dev_deploy: true
    secrets: inherit
  
  deploy_announcements_api:
    uses: ./.github/workflows/deploy_announcements.yml
    with:
      project_name: AnnouncementsAPI
      dev_deploy: true
    secrets: inherit
  
  deploy_adopter_api:
    uses: ./.github/workflows/deploy_adopter.yml
    with:
      project_name: AdopterAPI
      dev_deploy: true
    secrets: inherit