name: Release flutter app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true
      - name: Flutter get dependencies
        run: flutter pub get
      - name: Build release android apk
        run: flutter build apk --release
      - name: Make a release
        uses: softprops/action-gh-release@v1
        with:
          files: client/build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true
          prerelease: true
          tag_name: new_release
