name: Master merge workflows

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_client_app:
    permissions:
      contents: write
    uses: ./.github/workflows/deploy_client_app.yml
  
  deploy_shelter_api:
    uses: ./.github/workflows/deploy_API.yml
    with:
      project_name: ShelterAPI
    secrets:
      azure_app_service_publish_profile: ${{ secrets.PUBLISH_PROFILE_SHELTER_API }}
