name: Test dotnet APIs

on:
  workflow_call:
    inputs:
      path_to_project:
        default: apis/
        type: string

jobs:
  test_apis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path_to_project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Secrets set up
        uses: ./.github/actions/set_up_apis_secrets
        with:
          google_cloud_bucket_name: ${{ secrets.GOOGLE_CLOUD_BUCKET_NAME }}
          google_cloud_secret_type: ${{ secrets.GOOGLE_CLOUD_SECRET_TYPE }}
          google_cloud_secret_project_id: ${{ secrets.GOOGLE_CLOUD_SECRET_PROJECT_ID }}
          google_cloud_secret_private_key_id: ${{ secrets.GOOGLE_CLOUD_SECRET_PRIVATE_KEY_ID }}
          google_cloud_secret_private_key: ${{ secrets.GOOGLE_CLOUD_SECRET_PRIVATE_KEY }}
          google_cloud_secret_client_email: ${{ secrets.GOOGLE_CLOUD_SECRET_CLIENT_EMAIL }}
          google_cloud_secret_client_id: ${{ secrets.GOOGLE_CLOUD_SECRET_CLIENT_ID }}
          google_cloud_secret_auth_uri: ${{ secrets.GOOGLE_CLOUD_SECRET_AUTH_URI }}
          google_cloud_secret_token_uri: ${{ secrets.GOOGLE_CLOUD_SECRET_TOKEN_URI }}
          google_cloud_secret_auth_provider_x509_cert_url: ${{ secrets.GOOGLE_CLOUD_SECRET_AUTH_PROVIDER_X509_CERT_URL }}
          google_cloud_secret_client_x509_cert_url: ${{ secrets.GOOGLE_CLOUD_SECRET_CLIENT_X509_CERT_URL }}
      - name: Build APIs
        run: dotnet build --no-restore Backend.sln
      - name: Test APIs
        run: dotnet test /p:DefineConstants="TEST" --no-restore --verbosity normal
